### ISSUE TITLE
Dependencies...

### ISSUE THREAD

**Issue by stevenrbrandt** [Sbozzolo/kuibit#21]
kuibit depends on argcomplete and tikzplotlib. These were not installed during the execution of "pip3 install kuibit."

**Comment by Sbozzolo** [comment]
`tikzplotlib` and `argcomplete` were introduced as dependencies in `1.2.0`, but the latest version of `kuibit` on PyPI is `1.1.1`. 

I suspect that you are seeing this error because you are running the examples, which, at the moment, are not in-phase with the version of PyPI. This is a temporary accident due to the fact that I set up the pipeline to publish examples along with version `1.2.0`, which I am still testing. Everything will be solved once I release the stable version `1.2.0`. Once I do that, tagging on GitHub will automatically produce a new examples tarball and publish the new build to PyPI, so everything will always be synced (without any human intervention).

While waiting for `1.2.0`, you can install `kuibit` with
```
pip3 install -U git+https://github.com/Sbozzolo/kuibit.git
```
This is the most recent version.
