### ISSUE TITLE
Regarding ingestion of arbitrary asc files

### ISSUE THREAD

**Issue by irrationalnumbers** [Sbozzolo/kuibit#24]
I currently have a simulation using EinsteinAnalysis/Outflow which generates asc files at each detector. I can look at SD.allfiles and see the SimDir recognizes these files are located in the directory, but it does not create timeseries for the various columns. Is there an additional step that needs to be taken for these to be loaded? Or are asc files ingested with very strict format requirements?

Thanks,
Samuel

**Comment by Sbozzolo** [comment]
The best way to add support to Outflow is to output the quantities directly with Carpet:
```
CarpetIOASCII::out0D_vars                  = "
Outflow::outflow_flux
"
```
```
CarpetIOHDF5::out2D_vars  = "
Outflow::fluxdens_projected
"
```

I am not very familiar with the format used by Outflow, but if you already have the files, you can try manipulating them so that they look like as they were output by CarpetIOASCII. For the timeseries, that should easy. 

Alternatively, you can read the files manually with numpy, and create a TimeSeries from there. For each file, you would find the time and the value (probably first and second column), and create an object `TimeSeries` with those. Then, you invoke `combine_ts` to combine and clean them.

**Comment by irrationalnumbers** [comment]
@Sbozzolo thanks for the response. In the interim i did do it manually, the question was more to minimize effort and excess code in the future.  I will test adding the outflow to the 0D_vars as you mentioned and see if that will resolve this for the future.
